name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
  - title: "🐛 Bug Fixes"
    labels:
      - "bug"
  - title: "🧽 Cleanup"
    labels:
      - "cleanup"
exclude-labels:
  - "skip-changelog"
change-title-escapes: '\<*_&'
template: |
  ```
                                                              
                                                              
                                                              
                 ###########                                  
               #####                                          
              ###                                     #       
             ###                                     #        
             ##      #############  ##########       #        
            ###     #############   ###########     #         
            ##      #####                 ####     ##         
            #      #####    ###########  #####     #          
           ##      ####    #####         ####     ##          
           #      #####    ##################    ###          
          #      #####     #################     ##           
          #                                     ###           
         #                                     ###            
                                            #####             
                                    ###########               
                                                              
                                                              
                                                              
                           WHAT'S NEW                         
                                                              
                                                              
  ```

  $CHANGES
