# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.2.0
_src_path: gh:radio-aktywne/template-app-liquidsoap
accountname: radio-aktywne
appname: fusion
description: Audio streaming with Liquidsoap 🧼
docs: true
docsurl: https://radio-aktywne.github.io/app-fusion
envprefix: FUSION
imagename: apps/fusion
registry: true
releases: true
reponame: app-fusion
repourl: https://github.com/radio-aktywne/app-fusion
