# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.6.0
_src_path: gh:radio-aktywne/template-service-liquidsoap
accountname: radio-aktywne
description: Broadcast composing 🧼
docs: true
docsurl: https://radio-aktywne.github.io/dingo
envprefix: DINGO
imagename: services/dingo
registry: true
releases: true
reponame: dingo
repourl: https://github.com/radio-aktywne/dingo
servicename: dingo
