# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.6.0
_src_path: gh:radio-aktywne/template-service-liquidsoap
accountname: radio-aktywne
description: Broadcast composing 🧼
docs: true
docsurl: https://radio-aktywne.github.io/emifuse
envprefix: EMIFUSE
imagename: services/emifuse
registry: true
releases: true
reponame: emifuse
repourl: https://github.com/radio-aktywne/emifuse
servicename: emifuse
