name: Build

on:
  push:
    # trigger only on main branch
    branches:
      - main
    # trigger only on changes to the following files
    paths:
      - "fusion/src/**"
      - "Dockerfile"
      - ".github/workflows/build.yaml"
  pull_request:
    # trigger only on main branch
    branches:
      - main
    # trigger only on changes to the following files
    paths:
      - "fusion/src/**"
      - "Dockerfile"
      - ".github/workflows/build.yaml"

jobs:
  build:
    name: Test Docker build
    runs-on: ubuntu-latest
    steps:
      - # get repository code
        name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build the image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: fusion:latest
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, mode=max, scope=${{ github.workflow }}
