name: Publish a docker image

on:
  release:
    types:
      - published

jobs:
  docker-push:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - # get repository code
        name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/radio-aktywne/fusion:latest,ghcr.io/radio-aktywne/fusion:${{ github.event.release.tag_name }}
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, mode=max, scope=${{ github.workflow }}
