name: Docs

on:
  push:
    # trigger only on main branch
    branches:
      - main
    # trigger only on changes to the following files
    paths:
      - "fusion/docs/**"
      - ".github/workflows/docs.yaml"

# env for all jobs
env:
  PIP_CACHE_DIR: ~/.cache/pip
  # increase this value to manually reset cache
  CACHE_NUMBER: 0

jobs:
  docs:
    name: Deploy docs
    # better to use pinned version here
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache packages
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.PIP_CACHE_DIR }}
          key: ${{ runner.os }}-pkgs-${{ env.CACHE_NUMBER }}
      - name: Set up Python
        id: python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.6"
      - name: Set up pip cache
        run: ${{ steps.python.outputs.python-path }} -m pip config set global.cache-dir ${{ env.PIP_CACHE_DIR }}
      - name: Install mkdocs
        working-directory: fusion/docs
        run: ${{ steps.python.outputs.python-path }} -m pip install -r requirements.txt
      - name: Deploy docs
        working-directory: fusion/docs
        run: mkdocs gh-deploy --force
